### ISSUE TITLE
get_account_balance function

### ISSUE THREAD

**Issue by Jalmood** [andelf/tronpy#1]
get_account_balance function get only TRX. 

How can I get other tokens in the account?

**Comment by andelf** [comment]
get_account_balance is a short cut for `get_account()['balance']`

you can use: `get_account()['assetV2']`.

Will add a `get_asset_balance` next version.

Thanks.

**Comment by Jalmood** [comment]
Thank you very much for amazing works.

**Comment by karapy** [comment]
> assetV2

I was looking to learn how to get USDT balance of a tron address and send it using python but it seems there is no get_account()['assetV2'] any more
what is the solution to send USDT tron on trc20 ?
