### ISSUE TITLE
 Unauthorized for url: https://api.trongrid.io/wallet/getsignweight

### ISSUE THREAD

**Issue by lee-qinghua** [andelf/tronpy#102]
i cant not find the method in AllowList Requested Api

**Comment by reza-khalafi** [comment]
@lee-qinghua 
Did you find any answer for this? I have this problem.
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.trongrid.io/wallet/getsignweight
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.trongrid.io/wallet/getnodeinfo
```

**Comment by MrNaif2018** [comment]
Maybe you didn't provide the necessary authorization for it?

**Comment by reza-khalafi** [comment]
@MrNaif2018 
You mean need api_key in HTTPProvider? How to set it?

**Comment by MrNaif2018** [comment]
I mean you answered your own question :D
Tron(HTTPProvider(api_key="..."))
I doubt default keys still work
Also why even use trongrid if it's paid? Use ankr RPCs

**Comment by reza-khalafi** [comment]
@MrNaif2018 
Thank you so much. It's works now.
