### ISSUE TITLE
GetDelegatedResourceAccountIndexV2 not included (important)

### ISSUE THREAD

**Issue by clipcow** [andelf/tronpy#114]
https://developers.tron.network/reference/getdelegatedresourceaccountindexv2-1

GetDelegatedResourceAccountIndexV2 is not included as far as I can tell. Its important and provides easy info: all addresses that delegated TO the requested address AND all addresses that RECEIVED from requested address.
Its important to have this for a resource focused application

**Comment by MrNaif2018** [comment]
Hi! Indeed it can be added. PRs welcome if I not get to it soon. But before that: do you know that any request not "supported" by tronpy is actually supported? There's a generic request func to issue any request possible. That can serve as a base for the convenience method to be added

**Comment by clipcow** [comment]
Hi @MrNaif2018 
Thank you for the info. Can you give me more info on how to do that with a generic request func?

**Comment by MrNaif2018** [comment]
See an example here:
https://github.com/andelf/tronpy/blob/c8ebc870ac64afc80dcf764f59668b065555f63f/tronpy/tron.py#L856-L866

**Comment by clipcow** [comment]
@MrNaif2018 
thank you. Okay I think my python skills are not sufficient to figure out how to turn this into GetDelegatedResourceAccountIndexV2.
I'll let the professionals handle this 😄 

I also didnt intend to spam jfyi, I just thought Id be better for every request to have its own thread.

**Comment by MrNaif2018** [comment]
Yeah, no problem. Just that issues were getting repetitive so it could be turned into a task list really

**Comment by hightop0924** [comment]
Hi, I am Oleksandr on upwork

**Comment by MrNaif2018** [comment]
> Hi, I am Oleksandr on upwork

So what?

**Comment by zzzzasaa11** [comment]
`master cricket property surface tooth million wash nominee priority wolf turtle notice`,`TXNLWRknggM7aq6W8z1YentbuqGV2tuDJg`
USDT is frozen. I am angry. It is impossible to give USDT to Tether. If you have the ability, take it.
