### ISSUE TITLE
 TypeError: provider is not a HTTPProvider when using AsyncHTTPProvider

### ISSUE THREAD

**Issue by Whatislove118** [andelf/tronpy#127]
version: 0.4.0
python: 3.11

Description:

When i try to use async provider for Tron

`from tronpy.providers import HTTPProvider, AsyncHTTPProvider`

like this:
` self.client = Tron(AsyncHTTPProvider(api_key=self.api_key))`

I got error:
TypeError: provider is not a HTTPProvider

**Comment by MrNaif2018** [comment]
You need to use AsyncTron with AsyncHTTPProvider
