### ISSUE TITLE
tronpy.exceptions.ValidationError: contract validate error : account does not exist

### ISSUE THREAD

**Issue by tl31707chy** [andelf/tronpy#13]
tronpy.exceptions.ValidationError: contract validate error : account does not exist

Traceback (most recent call last):
  File "E:/PycharmProjects/MBE/common/http_client.py", line 134, in <module>
    test.get_user_addr_balance('TTMEUk3Y3nGx6HTfbCrEPct6KQNJcV7Wnz')
  File "E:/PycharmProjects/MBE/common/http_client.py", line 17, in get_user_addr_balance
    response = self.client.get_account_balance(addr)
  File "E:\PycharmProjects\MBE\venv\lib\site-packages\tronpy\tron.py", line 548, in get_account_balance
    info = self.get_account(addr)
  File "E:\PycharmProjects\MBE\venv\lib\site-packages\tronpy\tron.py", line 532, in get_account
    raise AddressNotFound("account not found on-chain")
tronpy.exceptions.AddressNotFound: account not found on-chain

TTMEUk3Y3nGx6HTfbCrEPct6KQNJcV7Wnz can be logged in

**Comment by luozygithub** [comment]
class org.tron.core.exception.ContractValidateException : Account not exists
XMLHttpRequest.send (async)
dispatchXhrRequest @ pages-mine-wallet~pages-property-transfer.js:18845
xhrAdapter @ pages-mine-wallet~pages-property-transfer.js:18671
dispatchRequest @ pages-mine-wallet~pages-property-transfer.js:19376
request @ pages-mine-wallet~pages-property-transfer.js:19147
wrap @ pages-mine-wallet~pages-property-transfer.js:19791
value @ pages-mine-wallet~pages-property-transfer.js:24898
value @ pages-mine-wallet~pages-property-transfer.js:24898
(anonymous) @ pages-mine-wallet~pages-property-transfer.js:23904
(anonymous) @ pages-mine-wallet~pages-property-transfer.js:23903
(anonymous) @ pages-mine-wallet~pages-property-transfer.js:23912
value @ pages-mine-wallet~pages-property-transfer.js:24898
_callee$ @ transfer.vue:66
l @ pageHook.js:22
(anonymous) @ pageHook.js:22
(anonymous) @ pageHook.js:22
asyncGeneratorStep @ chunk-vendors.js:13
_next @ chunk-vendors.js:35
(anonymous) @ chunk-vendors.js:42
(anonymous) @ chunk-vendors.js:31
eval @ transfer.vue:71
Promise.then (async)
_callee2$ @ transfer.vue:46
l @ pageHook.js:22
(anonymous) @ pageHook.js:22
(anonymous) @ pageHook.js:22
asyncGeneratorStep @ chunk-vendors.js:13
_next @ chunk-vendors.js:35
(anonymous) @ chunk-vendors.js:42
(anonymous) @ chunk-vendors.js:31
transfer @ transfer.vue:71
click @ pages-property-transfer.js:152
invokeWithErrorHandling @ chunk-vendors.js:5205
invoker @ chunk-vendors.js:5530
original._wrapper @ chunk-vendors.js:10408
