### ISSUE TITLE
I am unable to pay TRX when interacting with the contract

### ISSUE THREAD

**Issue by testhai001** [andelf/tronpy#131]
I am conducting asset cross chain transactions and need to pay TRX to the contract. I have tried many methods but have been unable to successfully pay TRX, GPT told me to use the call_value method to pass TRX values, but in reality, this method is not available. If you know, please guide me on how to pay TRX while calling the contract. Thank you.

![image](https://github.com/andelf/tronpy/assets/166693345/c1293309-3669-4ea6-82a5-2b0b4c1264f5)

**Comment by Ephraim-Akolo** [comment]
I don't know if this is still relevant but someone might still need this. The `with_transfer` method sets the call_value of your contract method. 
Use the with_transfer method instead of the call_value method.

**Comment by MrNaif2018** [comment]
This is documented in the docs. Don't trust AI for everything
Thank you for your guidance here @Ephraim-Akolo
