### ISSUE TITLE
Error : tronpy.exceptions.AddressNotFound: account not found on-chain

### ISSUE THREAD

**Issue by itsAPK** [andelf/tronpy#2]
Got error ` tronpy.exceptions.AddressNotFound: account not found on-chain` When I try to get Balance of address.

Code : 
 
```
from tronpy import Tron

from pprint import pprint

client = Tron(network='nile')

address=client.generate_address()['base58check_address']

pprint(client.get_account_balance(address))
```

Traceback : 

```
Traceback (most recent call last):
  File "tron.py", line 9, in <module>
    pprint(client.get_account_balance(address))
  File "G:\BOT\tipbot\env\lib\site-packages\tronpy\tron.py", line 517, in get_account_balance
    info = self.get_account(addr)
  File "G:\BOT\tipbot\env\lib\site-packages\tronpy\tron.py", line 501, in get_account
    raise AddressNotFound("account not found on-chain")
tronpy.exceptions.AddressNotFound: account not found on-chain
```

**Comment by itsAPK** [comment]
Got error tronpy.exceptions.AddressNotFound: account not found on-chain When I try to get Balance of address.

Code :

```
from tronpy import Tron

from pprint import pprint

client = Tron(network='nile')

address=client.generate_address()['base58check_address']

pprint(client.get_account_balance(address))
```

Traceback :

`Traceback (most recent call last): File "tron.py", line 9, in <module> pprint(client.get_account_balance(address)) File "G:\BOT\tipbot\env\lib\site-packages\tronpy\tron.py", line 517, in get_account_balance info = self.get_account(addr) File "G:\BOT\tipbot\env\lib\site-packages\tronpy\tron.py", line 501, in get_account raise AddressNotFound("account not found on-chain") tronpy.exceptions.AddressNotFound: account not found on-chain`

**Comment by KI5FPL** [comment]
You must use a faucet `http://nileex.io/join/getJoinPage` to get coin and activate your account on-chain.

**Comment by andelf** [comment]
You must use a faucet to get TRX and activate your account on-chian.

Faucet Page: https://nileex.io/join/getJoinPage
