### ISSUE TITLE
Padding bytes were not empty

### ISSUE THREAD

**Issue by ravikant2986** [andelf/tronpy#22]
Hello,
I am trying to decode TriggerSmartContract data parameter but getting error "Padding bytes were not empty" 

trx_abi.decode_abi(['address', 'uint256'], bytes.fromhex(param['data'])) 

please tell me how can I decode.

**Comment by congnghiakhiem** [comment]
I have same problem. I have extracted first 8 character for contract method. But some transaction have got error

if data[:8] == "a9059cbb":
  text = trx_abi.decode_abi(['address', 'uint256'], bytes.fromhex(data[8:]))
  print(text)
elif data[:8] == "23b872dd":
  text = trx_abi.decode_abi(['address', 'address', 'uint256'], bytes.fromhex(data[8:]))
print(text)

32108025 => block number
4c6e0524d6b8656d0ffe97042320da9f03aa8def25b360a7f202ec14f4767abe => transaction
000000000000000000000000002a9e91d7625c0bc85cf05cfe28e4341c28ae080000000000000000000000000000000000000000000000000000000114868ed0
('T9z64JoRNvbMEicZ5PCJhqkcauN5DUksge', 4639330000)

04ffeedd850c24b0a144360f295adac36e517ae694f328a4dd3cab609b5c2f6d
000000000000000000000000fbdba300903ce296b6c8789ca018fe7682cbe507000000000000000000000000f41ee1a3e3a18e2aa250ae9c1e490292985f86ba0000000000000000000000000000000000000000000000000000000039a143f0
('TYvuiqRqr74KXPXXgKx6ncJbX2tob6JtSa', 'TYDzsYUEpvnYmQk4zGP9sWWcTEd2MiAtW6', 966870000)

d61a5ca5fa27d574ebc79c6241574beb0475862c363345ddeeb9393bcd2540d3
0000000000000000000000416128ae4b8cdf4e4ef499457cc285e9d12c55fc5e00000000000000000000000000000000000000000000000000000001dcca1b00
Traceback (most recent call last):
  File "C:\Projects\PyTools\trc20\usdt_listener.py", line 98, in <module>
    asyncio.run(listen_usdt_transfer())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Projects\PyTools\trc20\usdt_listener.py", line 82, in listen_usdt_transfer
    check_trasaction(block["transactions"])
  File "C:\Projects\PyTools\trc20\usdt_listener.py", line 38, in check_trasaction
    text = trx_abi.decode_abi(['address', 'uint256'], bytes.fromhex(data[8:]))
  File "C:\Python39\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "C:\Python39\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Python39\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Python39\lib\site-packages\eth_abi\decoding.py", line 173, in decode
    yield decoder(stream)
  File "C:\Python39\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Python39\lib\site-packages\eth_abi\decoding.py", line 201, in decode
    self.validate_padding_bytes(value, padding_bytes)
  File "C:\Python39\lib\site-packages\eth_abi\decoding.py", line 332, in validate_padding_bytes
    raise NonEmptyPaddingBytes(
eth_abi.exceptions.NonEmptyPaddingBytes: Padding bytes were not empty: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00A'

**Comment by congnghiakhiem** [comment]
I change to use to_base58check_address for decode and it works

**Comment by ripinghot** [comment]
> I change to use to_base58check_address for decode and it works

hello @congnghiakhiem 
can you write down your code that how you fix this problem ?
i have the same problem and i dont figure it out

**Comment by congnghiakhiem** [comment]
`
def check_trasaction(trans):
    for trx in trans:
        trx_id = trx["txID"]
        
        if trx["ret"][0]["contractRet"] == "SUCCESS":
            contract = trx["raw_data"]["contract"][0]
            contract_type = contract["type"]

            if contract_type == "TriggerSmartContract":
                contract_address = contract["parameter"]["value"]["contract_address"]
                if contract_address == USDT_CONTRACT:
                                        
                    if data[:8] == "a9059cbb":
                        from_addr = contract["parameter"]["value"]["owner_address"]
                        to_addr = to_base58check_address('41' + (data[8:72])[-40:])
                        amount = int(data[-64:], 16)
                        ...

                    elif data[:8] == "23b872dd":
                        from_addr = to_base58check_address('41' + (data[8:72])[-40:])
                        to_addr = to_base58check_address('41' + (data[72:136])[-40:])
                        amount = int(data[-64:], 16)
                        ...
`

**Comment by MrNaif2018** [comment]
Fixed by b8b48ca4016a5a3f1a9acc0bbff7c929a8f9107f, originally introduced in #36

**Comment by MrNaif2018** [comment]
@long2ice Sorry for late reply, you probably figured this out by now, but the first 8 bytes is function selector, next are params
So you do:

```
from tronpy import Tron
from tronpy.abi import trx_abi

t = Tron()

tx = t.get_transaction("306dca0f8cff64625c2a46a6df917f10fe723eff2bcee54e9c2e5a600127567b")

contract_data = tx["raw_data"]["contract"][0]["parameter"]["value"]["data"]

print(trx_abi.decode_abi(["address", "uint256"], bytes.fromhex(contract_data[8:])))

> ('TPJNfTfBunWWqME2Povh6thCffaUDumkXV', 200000000)
```

There's also get_function_by_selector which may be useful if you have ABI loaded

**Comment by MrNaif2018** [comment]
In 64801a57b56e51203be1afc6339375d42592c5e1 I've added ability to parse such transactions via
trx_abi.decode_abi(["address", "uint256"], bytes.fromhex(contract_data[8:]), **strict=False**)

those transactions are still very rare and should ideally be fixed by those who send it, but this way you can disable the validation
disabling it completely makes no sense as it helps prevent errors when e.g. someone passed full contract data including it's method instead of just params data
