### ISSUE TITLE
Error on constructor contract

### ISSUE THREAD

**Issue by FelipeVillela** [andelf/tronpy#24]
Hello budy, how are you?
I had a problem with your library when trying to call the contract builder. When I create my contract in Solidity and compile it, it generates the abi and the byte code for me. However, an error is returned saying that my constructor does not exist. I noticed that in line 156 in the file 'contract.py' you check if the type is equal to "Constructor" but the generated abi is with the letter 'C' lowercase. I suggest replacing the line with:

method_abi['type'] == "constructor"

Thanks in advance!

**Comment by jjhesk** [comment]
#35 
did you make example of constructor valuables?

**Comment by MrNaif2018** [comment]
@FelipeVillela You're right, I've just checked e.g. USDT contract and constructor is lowercase
Fixed by cb9977288a27c84adc30ddefa1cde57d64e902fb
Please consider contributing more tests if you have time
