### ISSUE TITLE
AttributeError: 'AsyncClient' object has no attribute '_state'

### ISSUE THREAD

**Issue by congnghiakhiem** [andelf/tronpy#25]
This is my function:

async def create_account():
    async with AsyncTron(provider=AsyncHTTPProvider(api_key=[tronAPI1, tronAPI2, tronAPI3])) as client:
        print(client)

Exception ignored in: <function AsyncClient.__del__ at 0x0000021029ED0820>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\httpx\_client.py", line 1780, in __del__
    if self._state == ClientState.OPENED:
AttributeError: 'AsyncClient' object has no attribute '_state'

**Comment by MrNaif2018** [comment]
Should be fixed in recent httpx versions
