### ISSUE TITLE
How can I get TRC20&TRC721 info by block num? 

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [andelf/tronpy#26]

**Comment by MrNaif2018** [comment]
Hi! Not sure what exactly do you mean, but if you want to i.e. monitor all blocks for smart contract events, all that info is available in block data. 
If `contract["type"] == "TriggerSmartContract"`, then you can parse data from here
See example here:
https://github.com/bitcartcc/bitcart/blob/11e80ef0aec82a05ceaeca38649b184e46c354d8/daemons/trx.py#L93-L120
P.S. If you want to do payment processing you can just use BitcartCC directly (:
