### ISSUE TITLE
broadcast extra '/' cause change in the base url

### ISSUE THREAD

**Issue by aghamir** [andelf/tronpy#28]
Slash in the first of this line cause instead of the url like to https://example.com/trx-fullnode/wallet/broadcasttransaction convert to https://example.com/wallet/broadcasttransaction 
https://github.com/andelf/tronpy/blob/9e869fb508c3f77b432948cc56cd66985375843d/tronpy/tron.py#L869
If we remove the first '/' this works correctly.

**Comment by danielqba** [comment]
Sorry for keep asking if this is already merged, shouldn't be available in PyPi already?
