### ISSUE TITLE
Join public network

### ISSUE THREAD

**Issue by yermukhanbet** [andelf/tronpy#31]
From the examples it seems like everybody joins test network
clien = Toron(network='nile')

however, I want to know how to connect to main Tron network, so if i generate the wallet, I can check it in tronscan?

**Comment by amirkhalesi** [comment]
@yermukhanbet 
Greetings
as mentioned in docs, by using `client = Tron()` and not passing network keyword, you can connect to main network (via API key)
For further instructions, please refer to [Official Docs](https://tronpy.readthedocs.io/en/latest/client.html?highlight=account#calling-query-apis)

**Comment by MrNaif2018** [comment]
For mainnet there's also a reliable RPC available: https://rpc.ankr.com/http/tron
