### ISSUE TITLE
Please upgrade the version of httpx dep

### ISSUE THREAD

**Issue by max-block** [andelf/tronpy#32]
'httpx==0.16.1' -- it's too strict version.
 
So it's impossible to use tronpy in the projects with other deps which also use httpx as deps. httpx is 0.18.2 now

**Comment by behnamhatami** [comment]
Also ecdsa<0.16 is out of date, please upgrade it too.

**Comment by dwjorgeb** [comment]
also need this @andelf

**Comment by MrNaif2018** [comment]
Hi! In case someone needs it, I maintain a version of tronpy here with some fixes including this one:
https://github.com/bitcartcc/tronpy
It is used in production by us, fixes are mostly for AsyncTron, AsyncContract etc as we only use async interfaces

**Comment by andelf** [comment]
@MrNaif2018 Thanks, should I add you to tronpy's pip maintainer?

**Comment by MrNaif2018** [comment]
Fixed by b8b48ca4016a5a3f1a9acc0bbff7c929a8f9107f
