### ISSUE TITLE
Transaction raw data hex

### ISSUE THREAD

**Issue by Turosik** [andelf/tronpy#33]
Hello!
Is there any way to get raw_data_hex before broadcasting transaction?
I need that to calculate estimated net usage and find out if address net limit is enough for free transaction. Or may be there is another way to check if transaction will be free or not?
Thanks!

**Comment by MrNaif2018** [comment]
Use https://github.com/bitcartcc/trontxsize to reliably calculate transaction size (there's no other way to do it in python, I imported full node's protobuf files)
But ideally, you can use BitcartCC for this, i.e. set up bitcartcc daemon via https://docs.bitcartcc.com/deployment/ or manually:
```
git clone https://github.com/bitcartcc/bitcart
cd bitcart
pip install -r requirements/base.txt
pip install -r requirements/daemons/trx.txt
```

`TRX_SERVER=https://rpc.ankr.com/http/tron python3 daemons/trx.py`

Then using https://github.com/bitcartcc/bitcart-sdk or https://github.com/bitcartcc/bitcart/releases/tag/cli-1.1.0 or any other language, you can do stuff like this:

```python
from bitcart import TRX

coin = TRX(xpub="yourprivatekey")
transaction = coin.server.payto("address", amount, unsigned=True)
fee = coin.server.get_default_fee(transaction) # reliable in 100% of cases
# then sign and broadcast:
signed_tx = await coin.server.signtransaction(transaction)
tx_hash = await coin.broadcast(signed_tx)
```

**Comment by gtors** [comment]
Found out, that https://developers.tron.network/reference/getsignweight returns `raw_data_hex` in the response. 

```
client = tronpy.Tron()
txn = client.trx.transfer(pk., "...", 10 * tronpy.TRX).build().sign(pk)
raw_data_bytes = bytes.fromhex(client.get_sign_weight(txn)["transaction"]["transaction"]["raw_data_hex"])
```
