### ISSUE TITLE
My private tron full node can't work with tronpy

### ISSUE THREAD

**Issue by ye-gz-1996** [andelf/tronpy#45]
My private node can get the latest block,
client = Tron(HTTPProvider("my_address"))
client.get_latest_block_number()
Works fine, but client.generate_address() throws an error
The error message displayed is: account not found on-chain
I think it has something to do with me not filling in the api, but how does the private full node get the api?

**Comment by danielqba** [comment]
AFAIK client.generate_address() won't check if an address exists (is activated) on-chain. Can you try get_account_balance("address")?

**Comment by MrNaif2018** [comment]
`generate_address()` just creates a cryptographically random address without any network requests

But of course it won't exist in blockchain because it needs to be activated (1 TRX activation fee)
