### ISSUE TITLE
Contract. The functions provides. Transfer error

### ISSUE THREAD

**Issue by flllkis** [andelf/tronpy#47]
>>> txn = (
...         contract.functions.transfer('to address ', 1_000)
...         .with_owner('address ')  # address of the private key
...         .fee_limit(5_000_000)
...         .build()
...         .sign(priv_key)
... )
An error：
Traceback (most recent call last):
  File "zz.py", line 16, in <module>
    .sign(priv_key)
NameError: name 'priv_key' is not defined

**Comment by danielqba** [comment]
Looks like an error on your code, the var priv_key is not defined, did you do this before?

priv_key = "xxxxxxxxxxxxxxxxxx"
