### ISSUE TITLE
issue with httpx

### ISSUE THREAD

**Issue by Ad101DP** [andelf/tronpy#55]
I get this error when updating httpx to its latest version, which is needed by other libraries

_tronpy 0.2.6 requires httpx<0.17.0,>=0.16.1, but you have httpx 0.23.0 which is incompatible._

**Comment by andelf** [comment]
Could you try to use a clean and standalone venv from scratch?

**Comment by tor-web3** [comment]
Same problem, trying to fix version compatibility.

**Comment by MrNaif2018** [comment]
Fixed by b8b48ca4016a5a3f1a9acc0bbff7c929a8f9107f
