### ISSUE TITLE
Cut new release + add `code_hash` to Contract

### ISSUE THREAD

**Issue by RohitK89** [andelf/tronpy#57]
Hi @andelf. I noticed that logic was added two weeks ago to parse event logs, but there hasn't been a release since these changes. Could you please publish a new version when you can?

Secondly, I noticed that the `Contract` class doesn't have a field for `code_hash`, which is one of the keys returned in each contract object by Tron nodes. According to the Tron docs, it's the hash of the bytecode for the contract. See [here](https://github.com/tronprotocol/java-tron/blob/develop/Tron%20protobuf%20protocol%20document.md) for more.

Thanks!

**Comment by MioYvo** [comment]
Hi @RohitK89, commit 560d692ba5befde9996bd69fba84afc46d3a5ed8 added event_logs parser, so u can install from git and specify commit hash :
`pip install git+https://github.com/andelf/tronpy@560d692ba5befde9996bd69fba84afc46d3a5ed8`

**Comment by MrNaif2018** [comment]
Added `code_hash` in b8d9fe5ecb1cfe130dbb42ec6cf7b4c9d9d9438d
Also added missing `origin_address` in sync Contract version too

I will make a release soon
