### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by MioYvo** [andelf/tronpy#6]
Is there a schedule to support asyncio?
For example base on [aiohttp](https://github.com/aio-libs/aiohttp) or [httpx](https://github.com/encode/httpx) (better)

Thanks for the great work!
I'd like to give some PR to help this if you need. :>

**Comment by andelf** [comment]
Haven't figured out how to support both async and sync calling styles at the same time.😅

PRs are welcomed.
