### ISSUE TITLE
`ecdsa` should not be used in production !!!

### ISSUE THREAD

**Issue by yxy** [andelf/tronpy#60]
NOTE: This library should not be used in production settings, see Security for more details.

ref: https://pypi.org/project/ecdsa/#Security

**Comment by MrNaif2018** [comment]
Definitely I agree. Something like pycryptodome probably also has elliptic curve functions, this needs to be checked

**Comment by MrNaif2018** [comment]
I wonder what's better: cryptography or pycryptodome? Personally I like the former more

**Comment by MrNaif2018** [comment]
Actually cryptography is too complex :D
https://pypi.org/project/coincurve is a good fit as it's a libsecp256k1 wrapper
