### ISSUE TITLE
Claiming TRX's vote rewards

### ISSUE THREAD

**Issue by errais2000** [andelf/tronpy#61]
Hello,
I just want remembering you to implement a method that claim tron rewards (for voting for super representatives) .
Thank you,

**Comment by MrNaif2018** [comment]
Is it `VoteAssetContract`?

**Comment by andelf** [comment]
@MrNaif2018  No. `VoteAssetContract` is for voting TRC10.

https://github.com/opentron/opentron/blob/226282905ccfc043d7209e143eaf43477ee99cca/proto/proto/contract.proto#L151-L153

**Comment by MrNaif2018** [comment]
Fixed by 7e765a547fea1bf041e3f37c2c660b3c4cee4323
