### ISSUE TITLE
Shielded TRC20

### ISSUE THREAD

**Issue by karapy** [andelf/tronpy#67]
<tronpy.tron.Tron object at 0x0000018C27137FA0>
client.generate_zkey()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wallet\venv\lib\site-packages\tronpy\tron.py", line 498, in generate_zkey
    return self.provider.make_request("wallet/getnewshieldedaddress")
  File "C:\Users\wallet\venv\lib\site-packages\tronpy\providers\http.py", line 80, in make_request
    resp.raise_for_status()
  File "C:\Users\wallet\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.trongrid.io/wallet/getnewshieldedaddress

**Comment by danielqba** [comment]
When I go to that url, I get this:

`TronGrid service does not support this API`

Maybe it's trongrid fault this time?

**Comment by karapy** [comment]
is there anyway to do most task locally offline?
onething that I am looking for is to be able to have tron node in prune mode 
and notification service like what we have in bitcoin node

**Comment by karapy** [comment]
> is there anyway to do most task locally offline?
> onething that I am looking for is to be able to have tron node in prune mode
> and notification service like what we have in bitcoin node

is there anyway to do most task locally offline?
onething that I am looking for is to be able to have tron node in prune mode
and notification service like what we have in bitcoin node

**Comment by andelf** [comment]
These are unsafe APIs blocked by official trongrid.
You should deploy a local node.
Or else, there's a https://github.com/opentron/opentron/tree/master/ztron local implementation.
