### ISSUE TITLE
ETH-ABI

### ISSUE THREAD

**Issue by Whitev2** [andelf/tronpy#68]
I earnestly ask you to translate the project under eth-abi>=3.0.1

**Comment by Whitev2** [comment]
Version less than 3.0.0 causes conflict with library web3

**Comment by danielqba** [comment]
@andelf still active?

**Comment by MrNaif2018** [comment]
Hi! In case someone needs it, I maintain a version of tronpy here with some fixes including this one:
https://github.com/bitcartcc/tronpy
It is used in production by us, fixes are mostly for AsyncTron, AsyncContract etc as we only use async interfaces

**Comment by andelf** [comment]
@danielqba @MrNaif2018 I haven't worked in the crypto field for some days.
I need to transfer pip maintainer to anyone who wants.

**Comment by MrNaif2018** [comment]
I think yeah, I can handle it (+push permissions here to fix some bugs)
I am MrNaif on PyPI

**Comment by andelf** [comment]
Many thanks! @MrNaif2018 I just invited you to this project and PyPI Maintainer.

You can also reach me at [github_username]@gmail.com.

**Comment by MrNaif2018** [comment]
Thanks! I will start cleaning up issues and PRs in the next few hours and probably do a PyPI release soon :+1:

**Comment by MrNaif2018** [comment]
Fixed by b8b48ca4016a5a3f1a9acc0bbff7c929a8f9107f

**Comment by MrNaif2018** [comment]
Hi @andelf!
Is it possible for me to get admin role, or something like that?
I want to set up CircleCI here for automated testing and releases like I did here for example:
![изображение](https://user-images.githubusercontent.com/39452697/215872743-465e1a73-3d10-4fb8-8dba-74484b1531dd.png)
(or maybe if possible, a transfer to bitcartcc org where I can manage it all as an org admin, but it's up to you)

For now I've merged and resolved most issues, I want to set up tests, linting & formatting pipeline and then it's good to go

**Comment by Whitev2** [comment]
@MrNaif2018, many thanks!
