### ISSUE TITLE
 How do I get my trx20 balance and all transactions for an account

### ISSUE THREAD

**Issue by MaGua-Bishop** [andelf/tronpy#75]
I want to know, how can I get the balance of trx20 tokens of an address and get the list of transactions of a certain address, which bothered me for 2 months, I'm sorry I didn't find them from the source code and documentation

**Comment by MrNaif2018** [comment]
Hi! You can use
the balanceOf and decimals contract functions to get balance of an account in any contract
As for the transactions, I think you need an indexer or to track transactions in live mode, they are not provided by full node directly. But if you have a block range you can scan it for transactions to your address

**Comment by MrNaif2018** [comment]
If you have any further questions, feel free to re-open the issue
