### ISSUE TITLE
Link to  BitcartCC?

### ISSUE THREAD

**Issue by andelf** [andelf/tronpy#78]
This project is not sponsored by [BitcartCC](https://bitcartcc.com/).

Why there's a link on README?

**Comment by MrNaif2018** [comment]
Hi! Well, it is sponsored by my time spent on maintaining the project and fixing the bugs, replying the issues in time etc. I mean, it just tells the users that if they don't want to re-implement from scratch, they can rely on a ready implementation written here:
https://github.com/bitcartcc/bitcart/blob/master/daemons/trx.py

But it doesn't stop them from using tronpy in whatever way they wish, which now uses native cryptography for example which was quite a pain to code really. Sponsoring by development time is a thing (:

**Comment by MrNaif2018** [comment]
Closing this, but if you have any concerns feel free to tell them (:
