### ISSUE TITLE
freeze v2 is open, old freeze is closed

### ISSUE THREAD

**Issue by xfourat** [andelf/tronpy#86]
Freezing balance on nile stopped working, returned error with tronpy 0.3.0 (and 0.2.x):

`Contract validate error : freeze v2 is open, old freeze is closed`

**Comment by MrNaif2018** [comment]
Could you try with master? It's fixed, but new APIs are not yet added

**Comment by xfourat** [comment]
Done testing on nile, freezing is okay but cannot un/delegate resources, i can't find the right method for it.

**Comment by MrNaif2018** [comment]
Should be done by #87
I'll make a release today
