### ISSUE TITLE
USDT Transfer TRC-20

### ISSUE THREAD

**Issue by Offensive-Cyber** [andelf/tronpy#9]
Hello Sir.
I couldn't find any way to select a token and Transfer it via tronpy Please Help me.

**Comment by andelf** [comment]
Doc: <https://tronpy.readthedocs.io/en/latest/contract.html#trigger-call>

**Comment by Offensive-Cyber** [comment]
> Doc: https://tronpy.readthedocs.io/en/latest/contract.html#trigger-call

Thanks ❤️❤️
