### ISSUE TITLE
withdrawal for the unfreezed token function

### ISSUE THREAD

**Issue by mohsen158** [andelf/tronpy#90]
there is no withdrawal for the unfreezed token function.
which was updated in stake2

**Comment by MrNaif2018** [comment]
Do you mean withdraw legacy v1 staked funds? Please send the method you mean

**Comment by benyaminkarimi** [comment]
WithdrawExpireUnfreezeContract

**Comment by MrNaif2018** [comment]
Added `withdraw_stake_balance`
