### ISSUE TITLE
Estimated energy

### ISSUE THREAD

**Issue by arehovski** [andelf/tronpy#91]
In the updated tron blockchain now there is an API method, that returns an estimated energy of calling a smart contract.
https://developers.tron.network/reference/estimateenergy
It would be nice to include it into your client library.

**Comment by arehovski** [comment]
I've created a PR with neccesary changes.
https://github.com/andelf/tronpy/pull/92

**Comment by MrNaif2018** [comment]
Merged, thank you! Though triggerconstantconstant was there for a while and is pretty useful still
