### ISSUE TITLE
How to use `PrivateKey.fromhex()`?

### ISSUE THREAD

**Issue by krau5** [andelf/tronpy#96]
There is no exact explanation either in the documentation or in the `tronpy` repo with an example of `PrivateKey.fromhex()` usage and which data should I put inside.
I would be glad if someone gives me an explanation of this method, I may even contribute to the docs, so that no one will face this problem again.
If you have any questions, or my question seems unclear - you're welcome to ask the details

**Comment by MrNaif2018** [comment]
Hi! I mean, the fromhex method is to get the privatekey object created from privatekey string like in all blockchains (I think it starts with 0x, don't remember for sure). Because default Privatekey constructor accepts bytes only, so this factory method is needed

**Comment by krau5** [comment]
Hi, @MrNaif2018 👋🏻  If so, I have another question. How can I get a `PrivateKey`? I have a mnemonics, with mnemonics I can get like... everything? I have address and all the other fancy data, but I cannot find an information of how can I actually get the private key for the exact address to sign the transactions later

**Comment by MrNaif2018** [comment]
eth-account, see
https://github.com/bitcart/bitcart/blob/master/daemons/trx.py#L172

**Comment by krau5** [comment]
Thanks, I'll have a look! Please, don't close the issue right now, I'll close it by myself when the problem will be solved
